define start:
    declare function fun1 as 1;
    declare function fun2 as 1;
    declare variable A  list;
    declare variable B to vector3;
    declare variable C to vector3;

enddef;

define update:
    gen D;
    result  set <2,1>;
    result getY to D;
    if D is <2>,
        create <"prefab1">  at <1,1,0> to A,
        say A,
    end,
    else,
        fun1 <3>,
    end;
enddef;

define A fun1 B:
    if B greater than <0> or  B greater than <1.5>,
        rotate B,
    end;
enddef;
