define start:
    declare variable sp as vector2;
    declare variable cp as vector2;
    declare function round 1;
    declare variable left int;
    declare variable right int;
    declare global temp int;
    
enddef;

define update:
    if screen_touched,
        sp set <0,0>,
        cp set <0,0>,
        get <"touch_position"> to sp,
        get <"screen_position"> to cp,
        calculate <"sp - cp">,
        result getX to left,
        result getY to right,
        temp set as result,
        calculate <"(sqrt(left * left + right * right))">,
        calculate <"temp / result">,

        say result,
    end;
    #get <"camera"> to temp;
    #temp move result;
    #say result of temp;
    move result;
    calculate <"- ((5 - sqrt(2))/5*(5 - sqrt(2))/5)">;
    say result;
enddef;

define round speed:
    get <"position"> to debug;
    <"position"> change to speed in I;
    say debug;
enddef;
